apiVersion: v2
name: grafana
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "8.2.6"

dependencies:
  - name: grafana
    version: 6.29.5
    repository: https://grafana.github.io/helm-charts