grafana:
  replicas: 2
  image:
    repository: ghcr.io/trialstudio/grafana
    tag: 9.0.2

  grafana.ini:
    server:
      root_url: root_url = https://grafana-main.trial.studio/
    analytics:
      check_for_updates: true
      check_for_plugin_updates: true
    security:
      cookie_secure: true
      allow_embedding: false
      strict_transport_security: true
      content_security_policy: true
    users:
      allow_sign_up: false
      allow_org_create: false
    auth.anonymous:
      enabled: false
    auth.github:
      enabled: true
      allow_sign_up: true
      client_id: ${clientID}
      client_secret: ${clientSecret}
      scopes: user:email,read:org
      auth_url: https://github.com/login/oauth/authorize
      token_url: https://github.com/login/oauth/access_token
      api_url: https://api.github.com/user
      allowed_organizations: trialstudio
    log:
      mode: console
    log.console:
      level: info

  envFromSecret: grafana-github-oauth
  env:
    POSTGRES_HOST: grafana-postgres
    TZ: America/New_York
  
  useStatefulSet: false
  imageRenderer:
    enabled: false
  networkPolicy:
    enabled: false
  persistence:
    enabled: false

  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
    hosts:
      - grafana-main.trial.studio
    tls:
      - hosts:
          - grafana-main.trial.studio
        secretName: grafana-tls

  rbac:
    pspEnabled: false
    namespaced: true

  sidecar:
    plugins:
      enabled: false
    notifiers:
      enabled: false
    dashboards:
      enabled: true
      label: grafana_dashboard
      labelValue: "1"
      folder: /var/lib/grafana/dashboards/external
      folderAnnotation: grafana.trial.studio/dashboard-folder
#      searchNamespace: ALL
      provider:
        disableDelete: false
        allowUiUpdates: true
        foldersFromFilesStructure: true
    datasources:
      enabled: false
      label: grafana_datasource
      labelValue: "1"

  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: mimir
          type: prometheus
          url: http://mimir-grafana-mimir/prometheus
          access: proxy

  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: 'default'
          orgId: 1
          folder: ''
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/default

  dashboards:
    default:
      mimir-writes:
        url: "https://raw.githubusercontent.com/grafana/mimir/main/operations/mimir-mixin-compiled/dashboards/mimir-writes.json"
      mimir-alertmanager-resources:
        url: "https://raw.githubusercontent.com/grafana/mimir/main/operations/mimir-mixin-compiled/dashboards/mimir-alertmanager-resources.json"
      mimir-alertmanager:
        url: "https://raw.githubusercontent.com/grafana/mimir/main/operations/mimir-mixin-compiled/dashboards/mimir-alertmanager.json"
      mimir-compactor-resources:
        url: "https://raw.githubusercontent.com/grafana/mimir/main/operations/mimir-mixin-compiled/dashboards/mimir-compactor-resources.json"
      mimir-compactor:
        url: "https://raw.githubusercontent.com/grafana/mimir/main/operations/mimir-mixin-compiled/dashboards/mimir-compactor.json"
      mimir-config:
        url: "https://raw.githubusercontent.com/grafana/mimir/main/operations/mimir-mixin-compiled/dashboards/mimir-config.json"
      mimir-object-store:
        url: "https://raw.githubusercontent.com/grafana/mimir/main/operations/mimir-mixin-compiled/dashboards/mimir-object-store.json"
      mimir-overrides:
        url: "https://raw.githubusercontent.com/grafana/mimir/main/operations/mimir-mixin-compiled/dashboards/mimir-overrides.json"
      mimir-queries:
        url: "https://raw.githubusercontent.com/grafana/mimir/main/operations/mimir-mixin-compiled/dashboards/mimir-queries.json"
      mimir-reads-networking:
        url: "https://raw.githubusercontent.com/grafana/mimir/main/operations/mimir-mixin-compiled/dashboards/mimir-reads-networking.json"
      mimir-reads-resources:
        url: "https://raw.githubusercontent.com/grafana/mimir/main/operations/mimir-mixin-compiled/dashboards/mimir-reads-resources.json"
      mimir-writes-resources:
        url: "https://raw.githubusercontent.com/grafana/mimir/main/operations/mimir-mixin-compiled/dashboards/mimir-writes-resources.json"
      mimir-reads:
        url: "https://raw.githubusercontent.com/grafana/mimir/main/operations/mimir-mixin-compiled/dashboards/mimir-reads.json"
      mimir-rollout-progress:
        url: "https://raw.githubusercontent.com/grafana/mimir/main/operations/mimir-mixin-compiled/dashboards/mimir-rollout-progress.json"
      mimir-ruler:
        url: "https://raw.githubusercontent.com/grafana/mimir/main/operations/mimir-mixin-compiled/dashboards/mimir-ruler.json"
      mimir-scaling:
        url: "https://raw.githubusercontent.com/grafana/mimir/main/operations/mimir-mixin-compiled/dashboards/mimir-scaling.json"
      mimir-slow-queries:
        url: "https://raw.githubusercontent.com/grafana/mimir/main/operations/mimir-mixin-compiled/dashboards/mimir-slow-queries.json"
      mimir-tenants:
        url: "https://raw.githubusercontent.com/grafana/mimir/main/operations/mimir-mixin-compiled/dashboards/mimir-tenants.json"
      mimir-top-tenants:
        url: "https://raw.githubusercontent.com/grafana/mimir/main/operations/mimir-mixin-compiled/dashboards/mimir-top-tenants.json"
      mimir-writes-networking:
        url: "https://raw.githubusercontent.com/grafana/mimir/main/operations/mimir-mixin-compiled/dashboards/mimir-writes-networking.json"

postgres:
  replicaCount: 1
  name: postgres
  image:
    name: postgres
    version: 14