grafana:
  replicaCount: 2
  name: grafana
  image:
    name: ghcr.io/trialstudio/grafana
    version: 9.0.2

  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}

  ingress:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
    host: grafana.trial.studio
    paths:
      - path: /
        pathType: ImplementationSpecific
    tls:
      - secretName: grafana-tls
        hosts:
          - grafana.trial.studio

  resources: {}

postgres:
  replicaCount: 1
  name: postgres
  image:
    name: postgres
    version: 14

  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}
  resources: {}