apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres.name" . }}2
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: 31000
      targetPort: sql
      protocol: TCP
      name: sql
      nodePort: 31000
  selector:
    {{- include "postgres.selectorLabels" . | nindent 4 }}
