apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: i.bacangan@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-account-key
    solvers:
      - dns01:
          route53:
            region: us-east-2
            hostedZoneID: Z06285332QCWSWF1RDQBK
            accessKeyID: AKIA3QBWGPBXDTI43DJZ
            secretAccessKeySecretRef:
              name: route53-credentials
              key: AKIA3QBWGPBXDTI43DJZ