apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: route53-credentials
  namespace: cert-manager
spec:
  encryptedData:
    AKIA3QBWGPBXGQEVKV7N: AgC4LKpQVMqgg58K1raXyLcny7d/EPLzicuRD+m58aA6rnpQWGP6KH7DFqRyF1n3EunlznDuBmQPp2SoTK/eduWhhJkX9ebIdIJE7uICmooflTLQHYsbUkjcF50dZY2likURqi+E5lJMrYuGZV7XJbx+CR8jWiFut4coUjA6k5R9IdREpyEZegHFVffyEpI5iw1UZB9UxF3PeihdQvlmK1gb56G2Qh2ksvnAsi0TCJ0RXdmOmn0ZcgEftqLjNl/Jvi7qE1yQAA4f4Q0DXZ4VHlf/Se4tJOqsATkmu1pVzWcL01+9+jh8PuPd/G6byJjtX2uxXR2r/lTnovIcVNWJltuCC83/zjPo+krSR0YlAjARrObo+14yQmZhu6JRz5jUfWXWNOu2C3zc3VVMJm3DfF3OK7knCt7uff9FQwZtlexn0T0L47BhIN2k/IA5l0gVz2wny1v4XU0/PJTcybglF8TMF1MGEr8i73zwNZkjrKIfR9krav044TBLQ6ingrBQ2xhbrMY7asDjwkYdceK+HbMb98hKXAGsWW4yqUS/Ur3Cdz4ClbVjF6Tp0eJhVTWxG/dQPpXuH7rIlQuzLwFRtzKxjGNCPokNfIFnkfRTUlr3/EOjr+ARIXqYb8Yk4MJI2Vc0D0qKXVyH4Igck8AtPCFQ5i/pIZY3xDNQHf+/49+H+lVNiclfE+A4pEbl1PZaQgx8ucaCKwV3y+gTKkWBgUvWvtbi4To6dgHPyFfJyl0=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: route53-credentials
      namespace: cert-manager