apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: route53-credentials
  namespace: cert-manager
spec:
  encryptedData:
    AKIA3QBWGPBXIZ3NOCVH: AgBJyt0kZddzaqG7hUuIbbZ2Khv1BXGLHmyrJPnaf5pcyZYIVQQQLE7pHJ8QpsgFtpAjjYijSvVAt0c8hsVzABNIZOL6C5y9pHJEksAvkx09tIzXGgMCo/bIRw80TEIeY7LFuBJint4Yv5eFt6ur9fAzCyAFj+DY4n3c4Ud2BZm9K55BnciX2jlhjNzsB3XbfxavYxOOyStQgWwQjmJo9yLX3uloI00IsmU7M5aOtUGjIpDk67HCONUw+oJS/xiF+wH/l1j5+fzKHJqw4ygOglUGia5IxlL9JXpV96oWOtMHrSa+7XvoSLB7Ew/BrDwYcpi8Uii9upGKRaVpxDkxJPKkLKQUZZ75/IUH3Z8CGM6Xr/WXZhBhk6j9AsfcBUOzS6F0A7ys+TMB/fhueYgoUsVesJvOcX9ozDsXF7psN/07FWBUniCHjVhFjjp4GnW70Wt9fSOHUsNFvk11baLBTGLeObmdv9WVyT/EPhZtcH/lh3Wpvhz/+dPEe3ETPlf7J+CRdxtGCAejugQJbsI8MVAfwKgbY3pn6AJrCoIlqJS5eFwSE37e7F4hL10A3p3MI+AOhUL+OVepi5+ZsqQK1yDOhhX8hGkJ7A8BOBx9OhayPonlLaaBv2B/DRo6hpsw+1oznSIPUr3K5c4MW7Y3Vc6hYaopIZQvpecC1JbEA8V30SnNIVRVQm0pnIEhFsh79UcOzTUOGBmN7rBzUuDGSLyVo542f8s+U/Xqt3WC3gRcn8AAnsOe3wl8
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: route53-credentials
      namespace: cert-manager

