apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "ecr-login.fullname" . }}
  labels:
    {{- include "ecr-login.labels" . | nindent 4 }}
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    metadata:
      name: {{ include "ecr-login.fullname" . }}
    spec:
      template:
        metadata:
          name: {{ include "ecr-login.fullname" . }}
          labels:
            {{- include "ecr-login.selectorLabels" . | nindent 12 }}
        spec:
          restartPolicy: OnFailure
          serviceAccountName: {{ include "ecr-login.fullname" . }}
          containers:
            - name: awscli-kubectl
              image: ibacangan/awscli-kubectl:0.1.0
              envFrom:
                - secretRef:
                    name: aws-iam-ecr-pull
              command:
                - /bin/sh
                - -c
                - |
                  ECR_TOKEN=`aws ecr get-login-password --region $AWS_REGION`
                  echo got token $ECR_TOKEN

                  DOCKER_CONFIG=$(kubectl create secret docker-registry any \
                    --dry-run=client \
                    --output json \
                    --docker-server=https://790387652718.dkr.ecr.${AWS_REGION}.amazonaws.com \
                    --docker-username=AWS \
                    --docker-password="${ECR_TOKEN}" \
                    | jq -r '.data.".dockerconfigjson"')
                  echo config $DOCKER_CONFIG

                  cat <<EOF > secret.yaml
                  apiVersion: v1
                  kind: Secret
                  metadata:
                    name: ecr-login-secret
                    annotations:
                      replicator.v1.mittwald.de/replication-allowed: "true"
                      replicator.v1.mittwald.de/replication-allowed-namespaces: "test.*"
                  type: kubernetes.io/dockerconfigjson
                  data:
                    .dockerconfigjson: ${DOCKER_CONFIG}
                  EOF
                  cat secret.yaml

                  kubectl apply -f secret.yaml
                  echo "Secret was successfully updated at $(date)"