apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "ecr-login.fullname" . }}
  labels:
    {{- include "ecr-login.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "get"]