apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dex
spec:
  secretName: dex-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - trialstudio
  isCA: false
  privateKey:
    rotationPolicy: Always
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - dex.trial.studio
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
    group: cert-manager.io