apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-credentials
  namespace: dex
spec:
  encryptedData:
    GITHUB_CLIENT_ID: AgCU7SgsyeRICTWN8m+rrnFbSBSS457N9C2fFNR+5hgw4spQbmVFYEGesF+pLTElboNHp1pQmLnsZc9onBA7S0Inc4Nn5ABkT4vJ5TCmdG5wX+iy+ttC6VNku1aFRxgNVMflrl0i2fUTNe6ZWBr4XiLAPXXQPmlHvJGoYVFwn4UMiw0YDGPLaP7RanfyJGL5vOsKrEc5+pS5SLzgDkzTvZ5UbibWTP2sf6+p+jpkeDH7Oki9UUqv8mc892JwW9XynkYppkxiJEuLjMivU+QHSO2PsjKs5KBtBa+owOYW2m4ZDURItxlXkP0quBFl/Yy9ZFjIgYtQiqoXxBWoeNCqC0qcSI4jV3c25uWTy3LVfUjZbfUAMmQQcHC/+tgb4EuRpo05uIMTNrrlC+84CIQxxCXUt2AgCDKG3kvDkt7dgRCjAkKY9P5hitpJdP3J6R0RBL/yi8gfOOPt6/qinPfIrjEmBIt8yTs3md4t9sM2i5DfNLL+gqFne1dne2/609NVpvgWvJez2YFZyaGzNF5614pCpK19XAmb8AnjU+JPQGNHjqMs6+YSIib+HVatq4g7mDCn04Xo6iqRZvrUJ6sSU/E2RBEpQiFD09V9Hp6DB6jZ95XSszAfGnBVz9wo1eS0/XqcFAWPxq30HP0B5BnbIn1fhQaaBgj/m0R+dNy5seYeM8CyUfTbTS2TIhpbrTwFNW53wVjJAnDXDuSZZjkKUZo=
    GITHUB_CLIENT_SECRET: AgAWYT22aF0NwjXP0kUaj6Rx0Mdp7AYpKSjBWXbEJy2eTn3AeJ8qdNiBmeKqstad5ZurUvUf7PM+p1CxtthpM/KXiwtuo6GgCh0yfy6KSJLwOZ1bt9ORw9tWf0cs13XOoNFhnLSbTirczPHS/3y7oSJ57b8/mXiipPig/T/9dvCo3OsqxJZF1vU6BYxRI054u7M4wgb0bNlPSMZDf6kGtVSP0Cxofs8lqZgGQJabaAhKZAlpgv1WkXPzK200RreidkrKw+EOlqSKW/xDDWa/9bfK7nA+bRn0GGHD5SB8KZ2oSrRvY3pl+elZ2b68Z0nYRO+s2kELEZBaMiQIgUrd30memfI4rGXK6sVwoqvu0onl+W1mvVTAvHhTcYkNgGl3JFjdQRINo0MWyoaXsd7RHW0zezhkz9qpo4lk+VuIGnfh8mJcUhcJR8BBxs8QdQUUu8S6K+2kqPqGNOXPN7lHiDJSOD4bboIzPR8MumpGl4X9eMTlI4UnRuUIMLG3/YcNostJ3ecKNvp7YQiur6jqvhgVXYP3TUDDd1KwTPfW5hCWtpnOvrL6aWMkE/yMb4y64QVdbic4M/+cpM15Lqjh2t/UcfB62o14orYOhKRgEo6CPQ8JhkdRSWzYE2gpZg8R0l51v6T0o9HzN0Skx3EuixvgWkNTeENvd3JDcLHNFil/fAvIubduf+0sOGjjr9CA7X6lBoVobSCT0yi0cWcFwzvRvJ3mP5F+PYi3rPhMMG4=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-credentials
      namespace: dex
