apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-credentials
  namespace: dex
spec:
  encryptedData:
    GITHUB_CLIENT_ID: AgAzwAauXkdOueAFO7QVxOraJgx5cP5VPYl8FViFLaU6VOsWeqbmtJD+Rqs2KhNQSmOEQJeHoRonz50ocq5Uxf1f0qkPNLTQvtlUK5sCc0gw3CrUITGM56Tw2KSj3DIx3zbFUaASnjGTWb44widj2xvhUvegJz73RrtF9ZLeFXSi1HCX1FRgpk7wyGFvN3WeT+1m6s2qlHxfqI9KCz0g29jAwCMMpltlBtgLlhNjqlWR1SwKJVC2lULT06Cr1NKchr2cov7BWnlxFNBCi3p2VjX0IRZ58J0rfiobvIPydpOMZgOvesygfBhHiRYpiFDiyR0X5MOzZNJOslO1z4UYkr/w8AtQV5LDx90Jx7Ii4nbPpMoYANpMSW9GpUcKZKY2At7+Z+ggSy15siK9jhZ475cd9x+DsSf7yvvcW2yjKX84BaSJarF7Cd1IzZnNBoPf75frSjfpkmN9SL+S7ruWGxlarxzHrO/qRIITh99tEnErr0PhMQTYb60PV/iyERf8yoqXMeWwFxYXz7NYYWzqbjmuDs/BVUQMf38buCWSnrz6bD6Hz47p7EyzTPX5750s3i6mSCxkjo1WI6HVSXtKt1/EJfUMmmuy4kghcXnRjRCglwZ+Za2dhSeXKpdwmiKxJVvqntHUefLtO29zxFGrFMpNMoTEbfpTHlWc0UqdCkwOv03yqHHR0i7+aAIqyoPuAzAy/4f2Gk1kxmgX7yIqVSVpZ5xmfzw=
    GITHUB_CLIENT_SECRET: AgBIg6D8fewY/jJ/raePiQFsc2I6bt3AZGNa8EM2fuDx2cbP9A0vmWceNR6BbWrB/7fH8XKS9YCVlD8CWSiDyHBDMArpD7hBJDRXV/MoFcsVz5ncw9r791kq+qVuS5KobF0yN6Ey4THJH52nqgw8QkKR1lMregFErMe7zVQeZG9hV/4SkK10Wq0RUx0xPyFkMICiys8h/vAk2OWoq3iQEpmLuK60XH0tHD3LhnuI/1eHPY2etdQD6TcMULCXvTbkSyRozdtvusL+h4WV0wKiRuL+2IEHOfE+1qLygZkqsG11B7OfPHEQOa0AvF93/Op58TjlPZQufmr1rxlYYasuV8i6YuL7wj3+9azjLvfI61LsM8g0CcjrBxtXdBxNrsIUf1ZrveTcCpoTAG4tSo+2ZSLztaO+cDafsl0JL3bev8uEJfMMXO8O93jS7Te5YOOJ/ELxJtubx3p+iDxbGEoZHFmC6wghKrxmmNiXQYKyBGVsoB0MTyg7sbAsC+bHRxT3lb1Hfu6olMvvfGHJIuFuip2jIbGR1IRMIu7FEqCVJ5JtcT30Rr3Qi+Lx1H48QZdqQ4ExHU3ClUHgC9IYWirab7ydt7Fuii1qNYlb48OLiuE/hErsKuAvgbRzEvjTXwDm1pC5/hrbazZ8ruVvH315axwj9JUJs5XeEhfC2ZWvN1j5SZO/xjgmlW1viM8p7DWRleX52mnpGh8nZta5ZJ+Iz/zD8Dlwe9QfSHp24ohXsmrGq3rtkZIagv3Egg==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-credentials
      namespace: dex