apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-credentials
  namespace: dex
spec:
  encryptedData:
    GITHUB_CLIENT_ID: AgCVbBizvjBQ6+umpUT62krS7G+hh0e6g6Dmcf8bjpgDMnRpQkmMkwnkgV3OmiCc3BgVLKjg8uScM9NA8Fj7RTaZ5vvhJw2OLWg29TqTDvz0LUJPn6faW1UhLuvEie8swVClHDbrI2n9QoawJh+bDdK/IvpV5zT37u8lfEWdpdk6GmCjINNw1RW9pnVcBF2il2dFpEOGAFQHvAnVq2f42LvEI5WsMNYTg1qFVT/uCu0U5gvUaNYSEJagtdj2cTzcrIel+//5fZw29NEFn5JlunNI6jbBr/eGjAmIix2+DybZLI/dYHYWEAoC4pbFoTDk7tj1tap1jDajoQS+g8h/vfmocY6EsNMzYFRpiXefDuKoyV/pi7+3oyGR1RpWWwOU+7wJ8+Z6p+GdOKCdGT3X1T6ww9k2fk08ObMPLJBh65v/4C7DhitOc+6EVYcXJd2auH4F9eLKnrsdPDJU7yF7BjpcuOjzl7GDI9RLIKTh2aB7TEbGypUQXJ1WsBXL1QCAR12DLGlyQ0KP+unY7T7H+w1+Nhp9s/cQpixHVtS/ijMQDknhW/RSOjYprxDIufy8kFP+dRURsoNKi+9lSqyKPxTOIwWYuQNE1U3u9noLrv96zNuJ7esmL3KsiOsqlOw1xup89cAikrgAeXHVIu1sufaPcvHig3ACCr+V7JoPxAI6jM0Vb0O1fLI0SYpQ+uEC8iswoeZk6SiCwVuOY8rLw19uRWYJFg==
    GITHUB_CLIENT_SECRET: AgAf4YIGS1hQZCaNiRBh9836OV3/2Cumpv6QpykUxFEVjn3IOiwFaUFN/YWVECFLWfGboImFgareOp8037UhUly5NQY8st6CVE4CVPk0/wdUT2T2SzJTElc66jN567hptmYvWRoh7aGKNjDTDpBClhHwiHe4urzUM0De+OsKyFyyCSHxJGyEUnaUfe7ItPSXBtTY9icUp/Y5aNPXQq9f+352SqIetSbnz5q02+xDDaWoXA0PFRg6v6YMLV5dcE5YYfWM+iTXTcjdCOG5a0a4Kfoz9yykfWpLvqdBG474JDwX9AXY0g8i28e4IdDEptM5joTkJtFYV14/mIbnFDYHClPqGUTiN0xrwN00cMa4gQJkKsec2QbUqSsP3NxnaG7Hei8Q8ewY9arTwMYcJLTMr/ChqhLRZYEtCZ7azdrG7GsLCUrPn0PggUn8hhUPPTw+gojBK8p5tF5EeoAyBCzU0zgrIONeHnNqJk2jzQa6VuXH0adux6cPfb/6oNCx7lMdXy92LAUsEOVdsvq3K/5lPc735jNT+Tlus2u9VH8V/oxvzONWgRDR7van6/GknV9j/fLEkjfDR7JaF/ikEoyGuDA3aMFqtlufBE9zslzTV8lS1XJpU8uQ9/xEWKpmheZMwP86nz9vtM8gXR4iV/0FwzOkbZBc6TbYfsXQUyeGqpy/gzurMH4Bo8xJYt6DK6rU+1P84ti/MeXjSqintfMqhkC942yayCA6/3riigFaBCRS92ZesXmZvzQd
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-credentials
      namespace: dex
