apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-credentials
  namespace: dex
spec:
  encryptedData:
    GITHUB_CLIENT_ID: AgAudQWEWU3vkJkgETWAVoMhYoOaes3c5/5xoSi3/lc7lw891QUPekzQ5aqE5eoSBAwd5k11KoclnrGYdn6TrOFyTF5WrMtLUrhCV6uKC82gcLBVwLwrrTyqF+025lsCHYTF2Ov7m4pp1cSb66sraR7E03Ha7ttIGqhpphSyjFTz9fMlwCrw/QNyf3hFZHXq8QjDUrBm6O5wTWgX+xUEqzx817OUbCdKMf5hQ1UCF15B0lyfkKZO418eOcFopoWh/nMRRsAiybXJhg4FlWdi6eDICNMMCUGWyOFoijASJ+ufcqapK4buTNtjLmPjctgppHUsqXZJvBvYhp13FAlW0Y8Vpcx6rxGY0XBTtMyBtVp3Z/vhZ8+w9MGD5VgJxtZzwfOncpdOGJOFv3nNSAEkd7yzMG1Skl3XQU6b0LkQNgn4W1NPWLuqD1csHXa7KskcwWCJi0rmbg+bn3fql7DLZgm617YjNoZXjKvTO44RMoOe5NKXFpKHbZ/KVil9Iq1XTwFWv8r0cyrhY8D4xq0ChFDjOkMatWxyyUR+uASTfaTJjtsJp0UfRB6A2mFECn+/i2hSJyuNYR7K5rsVbrHsoLNoM7RM/Ik9KcEpVuqsSKCxjRlCz3qip2srrgHuNBiJS2/+fVWEcG5UUGg05CXZODw3E8Ftc9Wwsce8vj1QSTtjXe0q6dFbnESUMm75xsF5iuMcL16CsJB5f+xi3H1U387GXmmGxEo=
    GITHUB_CLIENT_SECRET: AgA2EgiU0g5C6r4iLbwLabPY1VwDAGOuSwJ8FgQaiq/0LMT5UJXYme24Tmh4zpZSqr0qWu2IxGSJ5dRN6tOBPlIRDhCsiV6mqLUhOAGyoipy/wlXzQWy7QwHxawKQRCQ2yYYBvzM+uMfXKbOawPlC6iX9KTGQ4H24iY+SYfRzyBzXtWALd7Dm0NcHbcifRBE7KyLUMw5Y9bITkU7VV0dkidPT2SRrUMx90rRRSuUHLPuwmkndLIIF5Laofd8xtoTI9pKD90ToReXdYqRe5akeRdhPsS4yA6G6xOYrau5UBa1GODYXgPjpKp7Jpsip7eS0hPbCZILpN8VIVZIHVB6L4FbgzPtUcZ50rW4ve3UvL8c2LFU912Vbywh6JGcMf7N5s9U11Wp8gxiH0QAhIa9Q3VUYEUmp/ULj634gulgVZfLXD39naBT+tXaAxXZfV8pSaMqp1aFnJaRa6abxD62g+VyrxPWTwUURCEpkcozCe7dEZ1MEoqh+9H+mm3galkQKj8CxIQJEowwmYLjtiqzej+1IynRKEVdXECfwY9Ka1mcxTZgQH45dLyuznab+rNvVltRedeu//tlvblekaCkqc3YHAUSh2U74M6rtKAmGw9BRKzVdVSJFNToZChyaf0WIC1BU79QYV0L4vB4CLqr6ZkexbnKPeVdgpF9bhxKnyS8M1lRmAUSBjsKgksfIdpxcb2V0HnoN8c3cTCSbzsztw8Kv8dqFblGVESA0pwri1maAuSGtFmxgvYJAQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-credentials
      namespace: dex

