apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-credentials
  namespace: dex
spec:
  encryptedData:
    GITHUB_CLIENT_ID: AgAM5l+OrpfNOdIGWMySkosA7tmOfZvNbT9GV3z460OjPuDjfg3o83IIcto1Cqm7zFq+GIDANySXJZxhkHA9IukG9BKMEXLLxB0X/teVuovTzC4N+ZHEUCY6ik0zhL7RkSYP77N8tL4R1BqNm7D8m/EOGO39G7XH9zLlq6sJ7SYXfNjGdJezSWlvhfBKnQScWJiFD/UpkySs4XzDkPCLiLW6pqjeHkGEEhRuVCsccCe80zwBuTJIA3wVm3l+P5DPmBDrNRI5ada/rNLRq0DFavEK1dNz6ImfTVpv5udgBjLwRN1RZxvFwlklqdmuvRG470Fw4M0rneMmGyra4orRJKkkHgAAcRN3aOWdXYLeBN6Xkrx4c5c6lmvfZKJTC6W8wynJmB8HPLHuEUq70/peNCmJ43dxdOUqk58/j+HRvDWNAUG8/MsaMcWqjejarsSMZjKY72c3lU2ujdrkYBfDh+TTd/5WLTarO6b9f8YNi3xgvSRNn1FM3L6KwWCsiE6qDFqI21i6hKgmNmQf2JT0Thd6TGzyGVoILuOw1ylGtnPCnV/l5VaXDxYLewIkD0ZOZfpucVTrpyLwAjkpo/ooty4/vcYCyVmuNlC1TjgQIPQxqhPx/OW/bMy7pezvd//jqIp9QQMACTbjc8CML11taDRANpjATWYgPD/WWvBjsfLM5+by4rP8dXGhFVWEQ2OfTU0/ZVzO+Z9WMNZqMl2VEKAoRt/KzQ==
    GITHUB_CLIENT_SECRET: AgC39ILCIJrye4BpRhPfxLCzzmp2pe1Q+kCqLEpCmy9Ge8Z6q1Q1hXJuGOvbMhJsZTtaTGbKafnxsocPq7HxIOuZlQfCXPV61NaEP0aeDKWIfI2PMgd+Gydci963ztTdXDPLUrT6WCBYEePHbYAo3PRfHtmRGRUXUE/2kD9k3x7p+rdTsBA/GAUCEXegVLn8Jgv2gpQ9ua142QEBIl/4Xnoh9ZIqv0v2n/zs0nYJEwwgs8KBrjuEBLgI7iy9Hk9VA0eKKikBE8HFb5XovnMWYVdPMVj0HgH+FGpDQXibjqclY2YGRD1Ow+wKohjY/sJKCos2sDWgTT/CxDG8/btxr6Ka1+r0I3BZ4HOPYBEi2NWcGf6BgQJ2IZARTmVlmylnSHUTQooYGonYAM3Brg+YzDD5PN9KfKaLbb+XDQhkOL9g8qg84nF1EnXRbX3ia2XuPvi72LrD5wPX7RESeqOeqfyzUlVMHJ4XbqUPVUgaJoXNSLU2Fhsi+dzv0aCuyAEs2ZoLgHp8NhkYh3oBwfemxh7Y5Kc/+GNB/S12SHi4AokV8yjWmlNDdAKZPDknT/NJ4q6sdVmQ+234/8ldXQl8dzfEyzTX5IAJcPYY3gEJjyCi+GAGJI+dBvQPr0jZGDUF4v4HKdKX08sAUTy8rEaDR8/dX2tChbasn+hQICLRzgH7Yj2LsnHo3G75/ilv/vPJIvWhT2ekodIuazramndJYnmEygN+3bzJuOk1pUG8Efp5aBkM6nZtAcTI
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-credentials
      namespace: dex