apiVersion: v1
kind: Secret
metadata:
  name: argo-install-git
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: git@github.com:trialstudio/argo_install.git