apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "grafana-mimir.fullname" . }}
data:
  config.yml: |
    target: all

    multitenancy_enabled: false

    memberlist:
      join_members:
        - {{ include "grafana-mimir.fullname" . }}-memberlist

    blocks_storage:
      backend: s3
      bucket_store:
        sync_dir: /tmp/mimir/tsdb-sync
      tsdb:
        dir: /tmp/mimir/tsdb
      s3:
        bucket_name: mimir-data
        endpoint: minio.storage:9000
        access_key_id: lokiAccess
        secret_access_key: lokiSecret
        insecure: true

    compactor:
      data_dir: /tmp/mimir/compactor

    ruler_storage:
      backend: s3
      s3:
        bucket_name: mimir-ruler
        endpoint: minio.storage:9000
        access_key_id: lokiAccess
        secret_access_key: lokiSecret
        insecure: true

    alertmanager_storage:
      backend: s3
      s3:
        bucket_name: mimir-alertmanager
        endpoint: minio.storage:9000
        access_key_id: lokiAccess
        secret_access_key: lokiSecret
        insecure: true