apiVersion: v1
kind: Service
metadata:
  name: {{ include "grafana-mimir.fullname" . }}-memberlist
  labels:
    {{- include "grafana-mimir.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http
      port: 7946
      targetPort: http-memberlist
      protocol: TCP
  selector:
    {{- include "grafana-mimir.selectorLabels" . | nindent 4 }}