kube-prometheus-stack:
  kubeControllerManager:
    enabled: false
  kubeProxy:
    enabled: false
  kubeScheduler:
    enabled: false
  prometheus:
    thanosService:
      enabled: true
    prometheusSpec:
      remoteWrite:
        - url: http://mimir-grafana-mimir/api/v1/push

  grafana:
    enabled: false
    forceDeployDashboards: true