mimir:
  image:
    name: grafana/mimir
    version: 2.0.0
    imagePullPolicy: IfNotPresent

  resources:
    limits:
      memory: 500Mi
    requests:
      cpu: 250m
      memory: 500Mi

  podAnnotations:
    likerd.io/inject: enabled

  podSecurityContext: {}
  securityContext: {}

agent:
  image:
    name: grafana/agent
    version: v0.24.1
    imagePullPolicy: IfNotPresent

  resources:
    limits:
      memory: 100Mi
    requests:
      cpu: 50m
      memory: 100Mi

  podAnnotations:
    likerd.io/inject: enabled

  podSecurityContext: {}
  securityContext: {}