mimir:
  image:
    name: grafana/mimir
    version: 2.0.0
    imagePullPolicy: IfNotPresent

  resources:
    limits:
      memory: 1000Mi
    requests:
      cpu: 500m
      memory: 1000Mi

  podAnnotations:
    likerd.io/inject: enabled

  podSecurityContext: {}
  securityContext: {}

agent:
  image:
    name: grafana/agent
    version: v0.24.2
    imagePullPolicy: IfNotPresent

  resources:
    limits:
      memory: 200Mi
    requests:
      cpu: 100m
      memory: 200Mi

  podAnnotations:
    likerd.io/inject: enabled

  podSecurityContext: {}
  securityContext: {}